version: '3.9'
services:

  #
  # janus-gateway
  # handles the WebRTC routing
  #
  janus-gateway:
    build:
      context: .
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    network_mode: "host" # needs linux platform
    
    restart: always


  # TODO: add ffmpeg command container

