version: '3.9'
services:

  #
  # mediamtx-gateway
  # handles the WebRTC routing
  #
  mediamtx-gateway:
    image: bluenviron/mediamtx:latest-ffmpeg
    network_mode: "host" # needs linux platform
    restart: always
    volumes: 
      - ./mediamtx.yml:/mediamtx.yml
    devices:
      - /dev/video0:/dev/video0
